[pytest]
#timeout = 180
addopts = -n auto
filterwarnings =
    ignore::DeprecationWarning
    ignore::urllib3.exceptions.InsecureRequestWarning
    ignore::ResourceWarning
    ignore:unclosed database:ResourceWarning
    ignore:.*ipywidgets.*:UserWarning
    ignore:.*include is ignored.*
