#!/bin/bash

# 모의투자 계좌 정보 (본인 정보로 수정)
#export SIM_APP_KEY="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
#export SIM_APP_SECRET="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
#export SIM_ACC_NUM="12345678-01"

# 실전투자 계좌 정보 (본인 정보로 수정)
#export REAL_APP_KEY="CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
#export REAL_APP_SECRET="DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"
#export REAL_ACC_NUM="87654321-01"

# 프로그램 실행
python3 main.py
